/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CollapsibleList: typeof import('./src/components/lists/CollapsibleList.vue')['default']
    DirectAccess: typeof import('./src/components/DirectAccess.vue')['default']
    ItemQtyActions: typeof import('./src/components/ItemQtyActions.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
